version: '2'
services:
  odoo:
    build: ./odoo-app
    ports:
     - 8069:8069
    volumes:
     - //h/trash/proj/odoo-kraskolba:/mnt/proj:ro
     - //h/trash/proj/odoo-kraskolba/Docker/odoo-dev-ecosys/odoo-app/odoo.conf:/etc/odoo.conf:ro
#     - //h/tmp/odoo-log:/mnt/log:rw
    links:
     - pg1:pg
#    command: /start
    depends_on:
     - pg1
#     - pgadm4
  pg1:
     build: ./pgsql
#  pgadm4:
#     image: fenglc/pgadmin4
#     volumes:
#      - //h/opt/docker/pgadmin4/.pgadmin:/root/.pgadmin:rw
#     ports:
#      - 5050:5050
#     links:
#      - pg1:pg1